server:
  port: 8090

spring:
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zx_cafeteria
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: AmberRedis
      database: 1 # 数据库索引，默认是0
      connect-timeout: 10000 # 连接超时时间，毫秒
      lettuce:
        pool:
          max-active: 8 # 最大连接数
          max-idle: 8 # 最大空闲连接数
          min-idle: 2 # 最小空闲连接数
          max-wait: 10000 # 最大等待时间，毫秒

# 自定义配置
zx:
  # jwt 密钥
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: lizhengxing_cafeteria_secret_key
    # 设置jwt过期时间，毫秒
    admin-ttl: 3600000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 设置用户jwt签名加密时使用的秘钥
    user-secret-key: lizhengxing_cafeteria_user_secret_key
    # 设置用户jwt过期时间，毫秒
    user-ttl: 3600000
    # 设置用户前端传递过来的令牌名称
    user-token-name: authorization
  # rsa 密钥
  rsa:
    # 公钥
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDL2Fg443yyk78Ox8CF/FTzDVtRlxFad7DCV0FyReCrbpFeJKymxcTZk5JYDS4ANEBP1oU8AqfM/5dGZibArffdk0PCSKFFJSGQhoZA3pSFRbP+1znyxdJgLrvXw0HkJnzzy+IJjqLlpVC8ExRgy8T+RYLypshb3T1p4nfLSQBmyQIDAQAB
    # 私钥
    private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAMvYWDjjfLKTvw7HwIX8VPMNW1GXEVp3sMJXQXJF4KtukV4krKbFxNmTklgNLgA0QE/WhTwCp8z/l0ZmJsCt992TQ8JIoUUlIZCGhkDelIVFs/7XOfLF0mAuu9fDQeQmfPPL4gmOouWlULwTFGDLxP5FgvKmyFvdPWnid8tJAGbJAgMBAAECgYAy2gSgJHfuIJdv+3rWse0LORDH2NTWabdps9S6yh3TBmEzSBjd/cYutPa0Co2oNWC5yf0wzETKChTV1hPiy0Niy83qyDL06oGyZAqH1eMzr8lH0qLrobMurRnELrcqqJ0se7v/ZjzTCoZNn5QebtgjZJF5sx2qH5m3ebdgZnL8gQJBAPc/S/CwGLHZp8bupY8yQAcjycI2f0b7w1dEvdlILIgOdb+7uY7E6Ec8XA+sX4iuuK/rTUhN/Yi1psE5ZA4yS3ECQQDTD7YmXxwcff68qlIJo/rh8a/0irhmCctTwU1cLscjzBjZLILavMoYpQaG8PgeO9UtSyJ0hPcrDbgVeI6RA7TZAkEAqqAA3TH5aMsG8M8CbAbGjubQtnl7blYSIWhsB8W6DY7FDbMURAV5Mqfh9GMFbsL861Jb+/jubWjGknPzq6Rj0QJAbprFMcaVzLiaTfRTmYm9Z7poIxavG4n2a6XZDH3XDgNe4jBZQpe8sL2KdhzBadahGGNPYxBrFrzRwy6yR3xRwQJAGqIAooEgby8KNV3AQrO6uyMYzg/W5EdiP6rNumjlcoLLJAZRBu5H7lSWXWnZDQblx/czk8ccO43v47io4e+wZw==
  # 文件上传
  file:
    # 文件存储根目录
    upload-path: D:/study/java/proj-upload-files/zx-cafeteria/files/
    # 访问文件的URL前缀
    access-prefix: /files/
  # 小程序
  wechat:
    # 小程序appid
    appid: wxd50b2e4c5274f61b
    # 小程序 secret
    secret: ef94683acda6816ab864d34d3ce4e19e
    # 小程序登录接口路径
    login-url: https://api.weixin.qq.com/sns/jscode2session

# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # XML映射文件的路径（支持通配符）
    mapper-locations: classpath*:mapper/**/*.xml
